### ISSUE TITLE
Gets error while make firmware.

### ISSUE THREAD

**Issue by k1asa** [homy-newfs8/esphome-sesame3#2]
My YAML is below.

```
esphome:
  name: esphome-web-******
  friendly_name: ESPHome Web ****** AtomS3

  libraries:
    - https://github.com/homy-newfs8/libsesame3bt#0.11.0
    - davetcc/TaskManagerIO @ ^1.4.0
  platformio_options:
    build_flags:
      - -std=gnu++17 -Wall -Wextra
      - -DMBEDTLS_DEPRECATED_REMOVED -DCONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED
      - -DTM_ENABLE_CAPTURED_LAMBDAS
# Configure the maximum number of connections as required
      - -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=4
    build_unflags:
      - -std=gnu++11

external_components:
  - source:
      type: git
      url: https://github.com/homy-newfs8/esphome-sesame3
      ref: v0.7.0
    components: [ sesame_lock, sesame_ble ]

esp32:
  #M5stack ATOM S3
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "********"

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-*****"
    password: "*******"

captive_portal:

lock:
  - platform: sesame_lock
    name: EntranceLockup
    id: entlock_up
    model: sesame_4
    tag: "sesame4"
    address: !secret sesame4_address
    secret: !secret sesame4_secret
    public_key: !secret sesame4_publickey
```

It gets error below.

```
INFO ESPHome 2023.12.9
INFO Reading configuration /config/esphome/esphome-web-a01388.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-web-a01388 (board: esp32-s3-devkitc-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.0.1
|-- libsesame3bt @ 0.11.0+sha.6e61d85
|-- TaskManagerIO @ 1.4.1
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
Compiling .pioenvs/esphome-web-a01388/src/esphome/components/sesame_lock/sesame_lock.cpp.o
Compiling .pioenvs/esphome-web-a01388/src/esphome/components/socket/lwip_sockets_impl.cpp.o
Compiling .pioenvs/esphome-web-a01388/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/esphome-web-a01388/src/esphome/components/web_server_base/web_server_base.cpp.o
In file included from src/esphome/components/sesame_lock/sesame_lock.cpp:1:
src/esphome/components/sesame_lock/sesame_lock.h:5:10: fatal error: esphome/components/sensor/sensor.h: No such file or directory
 #include <esphome/components/sensor/sensor.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/esphome-web-a01388/src/esphome/components/sesame_lock/sesame_lock.cpp.o] Error 1
========================== [FAILED] Took 4.92 seconds ==========================
```

What things I misstake?
sorry for my little English.
