### ISSUE TITLE
BLEの挙動　と　WPA-EAPについて

### ISSUE THREAD

**Issue by cocoabox** [homy-newfs8/esphome-sesame3#4]
はじめまして、素晴らしいLibありがとうございます。
（esphome素人ですので、ご容赦ください）

ちょっと１時間弱ハマりましたので、シェアいたします。
Macアドレス取得も無事終わりまして、設定は[sesame.yaml](https://github.com/homy-newfs8/esphome-sesame3/blob/main/sesame.yaml)ほぼそのまま使いましたが、

```
[00:34:56][E][genkan_lock:213]: Cannot connect to SESAME 30 times, reboot after 5 secs
```
reboot loopにハマりました。

以下を追加し、再度UPしても、同じエラーが出ました。
```
esp32_ble:
  enable_on_boot: false
```
ところが、上記設定を削除し、再度UPしたら、無事BLE接続できました。
理由は分かりませんが、とりあえず解決いたしました。

----

また、今検証環境はWPA2無線LANですが、本番環境ではEAP-TLS無線LANです。試しに

```
wifi:
  #ssid: "develop-musen"
  #password: "***"

  ssid: "prod-musen-eap"
  eap:
    identity: esp32forsesame 
    certificate_authority: ca-cert.pem
    certificate: client-cert.pem
    key: client-key.pem
```
を追加すると、WPA-EAP認証ができなくなりました。
同じ設定を空のPRojectに追加すると接続できると確認しました。もしかして、これは[libsesame3bt](https://github.com/homy-newfs8/libsesame3bt/tree/main/lib/libsesame3bt)の mbedtls/* がESPHome内部のTLS処理を干渉している？？かな、と疑っていますが、ESPHomeは今まで全く未経験ですので、結論には至りませんでした。

（esp-idfでEAP-TLS + mqttsアプリを作った時、似た問題もありました）

素人で大変恐縮ですが、何卒よろしくお願いいたします。m(_    _)m

**Comment by homy-newfs8** [comment]
報告ありがとうございます。

1点目は #3 と同じ原因のように思います。今のところESPHomeの他のBLE機能との共存ができません。
先程リリースしたv0.8.0ではビルド時のチェックでエラーになるよう変更しました。

2点目はよくわかりません。
mbedtlsですが、ベースとなるフレームワークarduino-esp32で無効になっている(使っていない)CMAC関連の関数を使うためにコピーしているだけなので、コンパイルエラーが出ない限り干渉するようなことはないものと思われます。

なお、v0.7.xまでのバージョンではESPHome起動時の(想定していたより)かなり早い段階でBLE接続を開始してしまうという問題がありました。v0.8.0で修正しましたので、WiFiへの影響がなくなり正しく接続されるようになっている可能性がありますので、お試しください。

**Comment by homy-newfs8** [comment]
ひとつ書き忘れました。。

v0.8.0からの対応になりますが、sesame_lockの起動タイミングを初期値よりさらに遅くすることが可能になっています。
`platform: sesame_lock`のブロック内で`setup_priority`を設定すると状況が改善するかもしれませんので、これもお試しください。

```
lock:
  - platform: sesame_lock
    setup_priority: -100
              :
```
